#pragma once

// Tracing
#define TRACE_INFO IOPORT_CREATE_PIN(PORTA, 5)
#define TRACE_WARN IOPORT_CREATE_PIN(PORTA, 6)
#define TRACE_ERR  IOPORT_CREATE_PIN(PORTA, 7)

#define PIEZZO_OUT IOPORT_CREATE_PIN(PORTA, 3)

// Share the trace pin
#define ALERT_OUTPUT_PIN TRACE_ERR
